name: contacts_app

environment:
  sdk: '>=1.8.5'

dependencies:
  polymer: ^0.15.5
  paper_elements: ^0.6.1
  core_elements: ^0.6.0+4
  appengine: ^0.2.5
  gcloud: ^0.1.3+1
  di: ^3.3.3
  route_hierarchical: ^0.6.1+1

transformers:
- polymer:
    entry_points:
    - web/index.html
- di
